name: Release Packages
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
        - 27017:27017

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --tags origin

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: extractions/setup-just@v1

    - uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: latest

    - name: Test
      run: |
        just test

    - name: Build
      run: |
        just build \
          ":snapshot?" ${{ github.ref_name != 'master' }} \
          ":include-unchanged?" false

    - name: Release
      env:
        CLOJARS_USERNAME: ci-kepler16-com
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: |
        just release \
          ":snapshot?" ${{ github.ref_name != 'master' }} \
          ":include-unchanged?" false \
          ":create-tags?" ${{ github.ref_name == 'master' }}
