name: Release Packages
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
        - 27017:27017
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --tags origin

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: 'maven'
        cache-dependency-path: '**/deps.edn'

    - uses: extractions/setup-just@v2
    - uses: DeLaGuardo/setup-clojure@13.0
      with:
        cli: latest
    - name: Setup Kmono
      uses: kepler16/setup-kmono@v1
      with:
        version: 4.7.3

    - name: Prep
      run: |
        kmono clojure -P ':*/*' -X :build:deps prep

    - name: Test
      run: |
        just test

    - name: Build
      run: |
        just build

    - name: Release
      if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: |
        just release
